name: eco_wallet
description: UniFacens EcoWallet mobile app for campus kitchen oil rewards.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  geolocator: ^13.0.4
  http: ^1.4.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
